# Generated by Django 4.0.6 on 2022-07-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220727_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featued_product',
            new_name='featured_product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
